# Generated by Django 4.2.4 on 2023-10-21 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0011_delete_balance_alter_creargasto_tipogasto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='miembro',
            name='grupo',
        ),
        migrations.RemoveField(
            model_name='miembro',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='creargasto',
            name='grupo',
        ),
        migrations.RemoveField(
            model_name='ingresaringresos',
            name='grupo',
        ),
        migrations.DeleteModel(
            name='Grupo',
        ),
        migrations.DeleteModel(
            name='Miembro',
        ),
    ]
