# Generated by Django 4.2.4 on 2023-11-01 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0014_gastocompartido'),
    ]

    operations = [
        migrations.AddField(
            model_name='creargasto',
            name='Frecuencia',
            field=models.CharField(choices=[('mensual', 'Mensual'), ('trimestral', 'Trimestral'), ('semestral', 'Semestral'), ('unico', 'Único')], default='unico', max_length=50),
        ),
        migrations.AlterField(
            model_name='creargasto',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
