# Generated by Django 4.2.4 on 2023-11-01 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0015_creargasto_frecuencia_alter_creargasto_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creargasto',
            name='important',
        ),
        migrations.AddField(
            model_name='creargasto',
            name='Importancia',
            field=models.CharField(choices=[('alto', 'Alto'), ('medio', 'Medio'), ('bajo', 'Bajo')], default='medio', max_length=50),
        ),
    ]
