# Generated by Django 4.2.4 on 2023-11-12 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0016_remove_creargasto_important_creargasto_importancia'),
    ]

    operations = [
        migrations.AddField(
            model_name='creargasto',
            name='FechaVencimiento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
