# Generated by Django 4.2.4 on 2023-11-13 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0019_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
